name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    name: Lint and Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Install dev dependencies
        run: uv pip install -e ".[dev]"

      - name: Ruff (lint)
        run: uv run ruff check .

      - name: Black (format check)
        run: uv run black --check .

      - name: isort (import order check)
        run: uv run isort --check-only .

      - name: Pytest
        run: uv run pytest -q
